// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNFwXpmcCu6pVvCxL_A2XJr6fhg7qbWEo',
    appId: '1:733016538785:web:8d0207fbe970f30efe7ae0',
    messagingSenderId: '733016538785',
    projectId: 'test-9395e',
    authDomain: 'test-9395e.firebaseapp.com',
    storageBucket: 'test-9395e.firebasestorage.app',
    measurementId: 'G-4DJ21HE9PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_v-RvWVJ7l8vB_fRKCFrv58ylBbL_FyY',
    appId: '1:733016538785:android:ea1a91d29510ecb1fe7ae0',
    messagingSenderId: '733016538785',
    projectId: 'test-9395e',
    storageBucket: 'test-9395e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xMY5AyrN9OUkiufvntVDfrIDWC0ZcPI',
    appId: '1:733016538785:ios:76a2cbd6fc5e16f0fe7ae0',
    messagingSenderId: '733016538785',
    projectId: 'test-9395e',
    storageBucket: 'test-9395e.firebasestorage.app',
    iosBundleId: 'com.example.kitahackHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xMY5AyrN9OUkiufvntVDfrIDWC0ZcPI',
    appId: '1:733016538785:ios:76a2cbd6fc5e16f0fe7ae0',
    messagingSenderId: '733016538785',
    projectId: 'test-9395e',
    storageBucket: 'test-9395e.firebasestorage.app',
    iosBundleId: 'com.example.kitahackHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNFwXpmcCu6pVvCxL_A2XJr6fhg7qbWEo',
    appId: '1:733016538785:web:015fc01f89690ca6fe7ae0',
    messagingSenderId: '733016538785',
    projectId: 'test-9395e',
    authDomain: 'test-9395e.firebaseapp.com',
    storageBucket: 'test-9395e.firebasestorage.app',
    measurementId: 'G-WEP0RGZ4YF',
  );

}